# Fetch latest image 
FROM mcr.microsoft.com/azure-sql-edge
# Set environment variables
ENV ACCEPT_EULA=1
ENV MSSQL_SA_PASSWORD=StrongPassword!123
# Using default
ENV MSSQL_PID=Developer
# Expose the SQL Server port
EXPOSE 1433
