on: 
  push:
    paths: 
     - '../../CheckMeInDB/**.sql'
  workflow_dispatch:
    

jobs:
  deploy-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "deploymatrix=$(ls ./CheckMeInDB/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      deploymatrix: ${{ steps.set-matrix.outputs.deploymatrix }}
  
  azuresql-deploy:
    needs: [deploy-setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployfiles: ${{ fromJson(needs.deploy-setup.outputs.deploymatrix) }}
      max-parallel: 1
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1                            # Azure login required to add a temporary firewall rule
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v2.3
      name: Deploy to AzureSQL
      with:  
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './${{ matrix.deployfiles }}'
        arguments: -b
