name: Deploy CheckMeIn Service API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: restore dependencies
        run: dotnet restore
      - name: dotnet Build
        run: dotnet build CheckMeInServices_Tests/CheckMeInServices_Tests.csproj
      - name: test
        run: dotnet test --verbosity normal
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      ## ------ propagate app settings -----------
      - uses: microsoft/variable-substitution@v1
        with:
          files: CheckMeInService/appsettings.json
        env:
          Entra.Instance: ${{ secrets.INSTANCE }}
          Entra.ClientId: ${{ secrets.CLIENTID }}
          Entra.TenantId: ${{ secrets.TENANTID }}
          AzureSQL.DataSource: ${{ secrets.DATASOURCE }}
          AzureSQL.UserId: ${{ secrets.USERID }}
          AzureSQL.Password: ${{ secrets.USER_PASSWORD }}
          AzureSQL.InitialCatalog: ${{ secrets.INITIALCATALOG }}
      ## ----------------------------------------
          
      - name: Build with dotnet
        run: dotnet build CheckMeInService/CheckMeInService.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/CheckInAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/CheckInAPI

  release:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD537CEC4DFA4711AEBCD5B8672C6D7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0547FCC0AB846CC96F898A12F2C3680 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6F7FD5707324223908101CED717126A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CheckMeInService'
          slot-name: 'Production'
          package: .
